default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: techemprez
  password: '9480';
  hostname: localhost
  port: 5432
development:
  <<: *default
  database: blog_app_development
test:
  <<: *default
  database: blog_app_test
production:
  <<: *default
  database: blog_app_production
  username: blog_app
  password: <%= ENV["BLOG_APP_DATABASE_PASSWORD"] %>
